using day_26_lesson.Models;
using System;
using System.Data.Entity;
using System.Linq;

namespace day_26_lesson.DL
{
    public class EmployeeDetailsModel : DbContext // a default class generated by EF code first approach
    {
        // Your context has been configured to use a 'EmployeeDetailsModel' connection string from your application's 
        // configuration file (App.config or Web.config). By default, this connection string targets the 
        // 'day_26_lesson.DL.EmployeeDetailsModel' database on your LocalDb instance. 
        // 
        // If you wish to target a different database and/or database provider, modify the 'EmployeeDetailsModel' 
        // connection string in the application configuration file.
        public EmployeeDetailsModel()
            : base("name=EmployeeDetailsModel")
        {
        }

        // Add a DbSet for each entity type that you want to include in your model. For more information 
        // on configuring and using a Code First model, see http://go.microsoft.com/fwlink/?LinkId=390109.

        public virtual DbSet<EmployeeDetailsEntities> EmployeeDetailsEntities { get; set; }
    }

    //public class EmployeeDetailsEntities                     
    //{
    //    public int Id { get; set; }
    //    public string Name { get; set; }
    //}
}